import type { DictationLesson } from '../types'

export const LESSON_DATABASE: Record<string, DictationLesson> = {
  // ── Category: Movie Short Clip ──
  kiki: {
    id: 'kiki',
    title: "Kiki's Delivery Service | English Trailer",
    category: 'Movie Short Clip',
    level: 'B1 - Intermediate',
    duration: '0:38',
    thumbnailUrl: 'https://img.youtube.com/vi/4bG17OYs-GA/hqdefault.jpg',
    description:
      'Classic Studio Ghibli trailer excerpt. Practice natural American English pronunciation and expressive delivery.',
    youtubeId: '4bG17OYs-GA',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 4.8,
        text: "I'm a witch, and this is my black cat, Jiji.",
        vi: 'Tôi là một phù thủy, và đây là chú mèo đen của tôi, Jiji.',
        ipa: '/aɪm ə wɪtʃ, ænd ðɪs ɪz maɪ blæk kæt, ˈdʒiː.dʒiː/',
      },
      {
        id: 1,
        start: 5.2,
        end: 9.0,
        text: "It's tradition for a witch to leave home when she turns thirteen.",
        vi: 'Theo truyền thống, một phù thủy sẽ phải rời nhà khi tròn 13 tuổi.',
        ipa: '/ɪts trəˈdɪʃ.ən fɔːr ə wɪtʃ tuː liːv hoʊm wɛn ʃiː tɜːrnz ˌθɜːrˈtiːn/',
      },
      {
        id: 2,
        start: 9.5,
        end: 14.0,
        text: 'I want to see the ocean and find a wonderful city of my own.',
        vi: 'Tôi muốn ngắm biển và tìm một thành phố tuyệt vời cho riêng mình.',
        ipa: '/aɪ wɑːnt tuː siː ðiː ˈoʊ.ʃən ænd faɪnd ə ˈwʌn.dɚ.fəl ˈsɪt.i əv maɪ oʊn/',
      },
      {
        id: 3,
        start: 14.5,
        end: 18.2,
        text: "Look at that! It's the most beautiful town I have ever seen.",
        vi: 'Nhìn kìa! Đó là thị trấn xinh đẹp nhất mà tôi từng thấy.',
        ipa: '/lʊk æt ðæt! ɪts ðə moʊst ˈbjuː.t̬ə.fəl taʊn aɪ hæv ˈɛv.ɚ siːn/',
      },
      {
        id: 4,
        start: 18.8,
        end: 22.8,
        text: 'Excuse me, do you have a witch living in this town?',
        vi: 'Xin lỗi, thị trấn này đã có phù thủy nào sinh sống chưa ạ?',
        ipa: '/ɪkˈskjuːz miː, duː juː hæv ə wɪtʃ ˈlɪv.ɪŋ ɪn ðɪs taʊn?/',
      },
      {
        id: 5,
        start: 23.2,
        end: 27.5,
        text: 'I have decided to start my very own delivery service!',
        vi: 'Tôi đã quyết định mở dịch vụ giao hàng của riêng mình!',
        ipa: '/aɪ hæv dɪˈsaɪ.dɪd tuː stɑːrt maɪ ˈvɛr.i oʊn dɪˈlɪv.ɚ.i ˈsɜːr.vɪs!/',
      },
      {
        id: 6,
        start: 28.0,
        end: 32.2,
        text: 'Flying is the only thing that I am really good at.',
        vi: 'Bay lượn là điều duy nhất mà tôi thực sự giỏi.',
        ipa: '/ˈflaɪ.ɪŋ ɪz ðiː ˈoʊn.li θɪŋ ðæt aɪ æm ˈrɪə.li ɡʊd æt/',
      },
      {
        id: 7,
        start: 33.0,
        end: 38.0,
        text: 'Sometimes we need to take a break and find our inspiration again.',
        vi: 'Đôi khi chúng ta cần phải nghỉ ngơi và tìm lại nguồn cảm hứng của mình.',
        ipa: '/ˈsʌm.taɪmz wiː niːd tuː teɪk ə breɪk ænd faɪnd ˈaʊ.ɚ ˌɪn.spəˈreɪ.ʃən əˈɡɛn/',
      },
    ],
  },
  spirited: {
    id: 'spirited',
    title: 'Spirited Away | English Dub Trailer',
    category: 'Movie Short Clip',
    level: 'B1 - Intermediate',
    duration: '0:20',
    thumbnailUrl: 'https://img.youtube.com/vi/ByXuk9QqQkk/hqdefault.jpg',
    description:
      'Chihiro’s adventure into a mysterious spirit world. Practice descriptive narrative sentences with emotional inflection.',
    youtubeId: 'ByXuk9QqQkk',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 4.8,
        text: 'Chihiro and her parents are moving to a brand new home.',
        vi: 'Chihiro và bố mẹ cô bé đang chuyển đến một ngôi nhà hoàn toàn mới.',
        ipa: '/tʃɪˈhɪə.roʊ ænd hɜːr ˈpɛr.ənts ɑːr ˈmuː.vɪŋ tuː ə brænd nuː hoʊm/',
      },
      {
        id: 1,
        start: 5.5,
        end: 9.5,
        text: 'They stumble upon an abandoned amusement park hidden in the woods.',
        vi: 'Họ tình cờ bước vào một công viên giải trí bỏ hoang ẩn sâu trong rừng.',
        ipa: '/ðeɪ ˈstʌm.bəl əˈpɑːn ən əˈbæn.dənd əˈmjuːz.mənt pɑːrk ˈhɪd.ən ɪn ðə wʊdz/',
      },
      {
        id: 2,
        start: 10.0,
        end: 14.5,
        text: 'You must never forget your real name if you want to find your way home.',
        vi: 'Bạn tuyệt đối không được quên tên thật nếu muốn tìm đường về nhà.',
        ipa: '/juː mʌst ˈnɛv.ɚ fɚˈɡɛt jɔːr ˈriː.əl neɪm ɪf juː wɑːnt tuː faɪnd jɔːr weɪ hoʊm/',
      },
      {
        id: 3,
        start: 15.0,
        end: 19.5,
        text: 'Once you have met someone, you never really forget them.',
        vi: 'Một khi bạn đã gặp ai đó, bạn sẽ không bao giờ thực sự quên được họ.',
        ipa: '/wʌns juː hæv mɛt ˈsʌm.wʌn, juː ˈnɛv.ɚ ˈrɪə.li fɚˈɡɛt ðɛm/',
      },
    ],
  },
  insideout: {
    id: 'insideout',
    title: 'Inside Out 2 | Official Trailer',
    category: 'Movie Short Clip',
    level: 'B2 - Upper Intermediate',
    duration: '0:20',
    thumbnailUrl: 'https://img.youtube.com/vi/LEjhY15eCx0/hqdefault.jpg',
    description:
      'Riley enters teenage years with new emotions. Practice rapid dialogue, modern idioms, and lively pacing.',
    youtubeId: 'LEjhY15eCx0',
    sentences: [
      {
        id: 0,
        start: 1.2,
        end: 5.0,
        text: 'Things have been great, but Riley is suddenly growing up so fast.',
        vi: 'Mọi thứ từng rất tuyệt vời, nhưng Riley đột nhiên lớn lên quá nhanh.',
        ipa: '/θɪŋz hæv biːn ɡreɪt, bʌt ˈraɪ.li ɪz ˈsʌd.ən.li ˈɡroʊ.ɪŋ ʌp soʊ fæst/',
      },
      {
        id: 1,
        start: 5.5,
        end: 9.8,
        text: 'Make room for the new emotions: Anxiety, Envy, and Embarrassment!',
        vi: 'Hãy nhường chỗ cho những cảm xúc mới: Lo Âu, Ganh Tị và Ngượng Ngùng!',
        ipa: '/meɪk ruːm fɔːr ðə nuː ɪˈmoʊ.ʃənz: æŋˈzaɪ.ə.ti, ˈɛn.vi, ænd ɪmˈbær.əs.mənt!/',
      },
      {
        id: 2,
        start: 10.5,
        end: 14.8,
        text: "I'm Anxiety, where can I put my stuff?",
        vi: 'Tôi là Lo Âu, tôi có thể để đồ của mình ở đâu đây?',
        ipa: '/aɪm æŋˈzaɪ.ə.ti, wɛr kæn aɪ pʊt maɪ stʌf?/',
      },
      {
        id: 3,
        start: 15.2,
        end: 19.5,
        text: 'We need to work together to protect who Riley really is.',
        vi: 'Chúng ta cần hợp tác cùng nhau để bảo vệ con người thật của Riley.',
        ipa: '/wiː niːd tuː wɜːrk təˈɡɛð.ɚ tuː prəˈtɛkt huː ˈraɪ.li ˈrɪə.li ɪz/',
      },
    ],
  },

  // ── Category: Daily Conversation ──
  coffee_order: {
    id: 'coffee_order',
    title: 'Ordering Coffee at a Cafe | Everyday English',
    category: 'Daily Conversation',
    level: 'A2 - Pre-Intermediate',
    duration: '0:25',
    thumbnailUrl: 'https://img.youtube.com/vi/YykjpeVGsIE/hqdefault.jpg',
    description:
      'Everyday cafe dialogue for ordering beverages and paying at the counter. Learn natural, polite expressions.',
    youtubeId: 'YykjpeVGsIE',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 5.0,
        text: 'Hi there! What can I get started for you today?',
        vi: 'Xin chào! Hôm nay tôi có thể chuẩn bị món gì cho bạn?',
        ipa: '/haɪ ðɛr! wʌt kæn aɪ ɡɛt ˈstɑːr.tɪd fɔːr juː təˈdeɪ?/',
      },
      {
        id: 1,
        start: 5.5,
        end: 10.0,
        text: 'Can I please have an iced caramel latte with oat milk?',
        vi: 'Cho tôi một ly latte caramel đá với sữa yến mạch được không?',
        ipa: '/kæn aɪ pliːz hæv ən aɪst ˈkær.ə.məl ˈlɑː.teɪ wɪð oʊt mɪlk?/',
      },
      {
        id: 2,
        start: 10.5,
        end: 15.0,
        text: 'Sure thing! What cup size would you like for that drink?',
        vi: 'Chắc chắn rồi! Bạn muốn chọn cỡ ly nào cho đồ uống này?',
        ipa: '/ʃʊr θɪŋ! wʌt kʌp saɪz wʊd juː laɪk fɔːr ðæt drɪŋk?/',
      },
      {
        id: 3,
        start: 15.5,
        end: 20.5,
        text: 'A medium would be great, and please make it less sweet.',
        vi: 'Cỡ vừa là được ạ, và làm ơn cho ít ngọt giúp tôi nhé.',
        ipa: '/ə ˈmiː.di.əm wʊd biː ɡreɪt, ænd pliːz meɪk ɪt lɛs swiːt/',
      },
    ],
  },
  airport_checkin: {
    id: 'airport_checkin',
    title: 'At the Airport Check-in Counter | Travel English',
    category: 'Daily Conversation',
    level: 'B1 - Intermediate',
    duration: '0:28',
    thumbnailUrl: 'https://img.youtube.com/vi/sX8M8t8mJ0g/hqdefault.jpg',
    description:
      'Airport check-in procedures, handling baggage drop-off, and boarding pass instructions.',
    youtubeId: 'sX8M8t8mJ0g',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 5.5,
        text: 'Good morning. May I please see your passport and flight booking?',
        vi: 'Chào buổi sáng. Tôi có thể kiểm tra hộ chiếu và mã đặt vé của bạn không?',
        ipa: '/ɡʊd ˈmɔːr.nɪŋ. meɪ aɪ pliːz siː jɔːr ˈpæs.pɔːrt ænd flaɪt ˈbʊk.ɪŋ?/',
      },
      {
        id: 1,
        start: 6.0,
        end: 11.0,
        text: 'Here you go. I have one checked bag and this small backpack as carry-on.',
        vi: 'Đây thưa bạn. Tôi có một kiện hành lý ký gửi và một chiếc balo xách tay.',
        ipa: '/hɪr juː ɡoʊ. aɪ hæv wʌn tʃɛkt bæɡ ænd ðɪs smɔːl ˈbæk.pæk æz ˈkær.i.ɑːn/',
      },
      {
        id: 2,
        start: 11.5,
        end: 16.5,
        text: 'Please place your suitcase onto the luggage scale to check its weight.',
        vi: 'Xin vui lòng đặt va li của bạn lên cân hành lý để kiểm tra trọng lượng.',
        ipa: '/pliːz pleɪs jɔːr ˈsuːt.keɪs ˈɑːn.tuː ðə ˈlʌɡ.ɪdʒ skeɪl tuː tʃɛk ɪts weɪt/',
      },
      {
        id: 3,
        start: 17.0,
        end: 22.5,
        text: 'Here is your boarding pass. The boarding gate will open at nine thirty.',
        vi: 'Đây là thẻ lên máy bay của bạn. Cửa khởi hành sẽ mở lúc chín giờ ba mươi.',
        ipa: '/hɪr ɪz jɔːr ˈbɔːr.dɪŋ pæs. ðə ˈbɔːr.dɪŋ ɡeɪt wɪl ˈoʊ.pən æt naɪn ˈθɜːr.t̬i/',
      },
    ],
  },
  asking_directions: {
    id: 'asking_directions',
    title: 'Asking for Directions in the City | Street English',
    category: 'Daily Conversation',
    level: 'A2 - Pre-Intermediate',
    duration: '0:24',
    thumbnailUrl: 'https://img.youtube.com/vi/xR26Q4Uv8uI/hqdefault.jpg',
    description:
      'Essential travel expressions for asking and navigating city streets and transit stations.',
    youtubeId: 'xR26Q4Uv8uI',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 5.5,
        text: 'Excuse me, could you tell me how to get to the central train station?',
        vi: 'Xin lỗi, bạn có thể chỉ cho tôi đường đến ga xe lửa trung tâm được không?',
        ipa: '/ɪkˈskjuːz miː, kʊd juː tɛl miː haʊ tuː ɡɛt tuː ðə ˈsɛn.trəl treɪn ˈsteɪ.ʃən?/',
      },
      {
        id: 1,
        start: 6.0,
        end: 11.0,
        text: 'Walk straight ahead for two blocks, then take a left turn at the traffic light.',
        vi: 'Hãy đi thẳng hai dãy nhà, sau đó rẽ trái ở chỗ đèn giao thông.',
        ipa: '/wɔːk streɪt əˈhɛd fɔːr tuː blɑːks, ðɛn teɪk ə lɛft tɜːrn æt ðə ˈtræf.ɪk laɪt/',
      },
      {
        id: 2,
        start: 11.5,
        end: 16.0,
        text: 'Is it within walking distance or should I take a city bus?',
        vi: 'Nó có ở trong khoảng cách đi bộ được không hay tôi nên bắt xe buýt?',
        ipa: '/ɪz ɪt wɪˈðɪn ˈwɔː.kɪŋ ˈdɪs.təns ɔːr ʃʊd aɪ teɪk ə ˈsɪt.i bʌs?/',
      },
      {
        id: 3,
        start: 16.5,
        end: 21.0,
        text: 'It only takes about five minutes on foot from here, right across the park.',
        vi: 'Chỉ mất khoảng năm phút đi bộ từ đây thôi, ngay đối diện công viên.',
        ipa: '/ɪt ˈoʊn.li teɪks əˈbaʊt faɪv ˈmɪn.ɪts ɑːn fʊt frʌm hɪr, raɪt əˈkrɔːs ðə pɑːrk/',
      },
    ],
  },

  // ── Category: IPA & Pronunciation ──
  ipa_vowels: {
    id: 'ipa_vowels',
    title: 'English Vowel Sounds: /iː/ vs /ɪ/ | Ship vs Sheep',
    category: 'IPA & Pronunciation',
    level: 'A2 - Pre-Intermediate',
    duration: '0:22',
    thumbnailUrl: 'https://img.youtube.com/vi/d6U1X-7eUjY/hqdefault.jpg',
    description:
      'Differentiate short /ɪ/ and long /iː/ vowel sounds in English using minimal contrast pairs.',
    youtubeId: 'd6U1X-7eUjY',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 5.0,
        text: 'Listen carefully to the distinct sound difference between ship and sheep.',
        vi: 'Hãy lắng nghe cẩn thận sự khác biệt phát âm rõ rệt giữa con tàu (ship) và con cừu (sheep).',
        ipa: '/ˈlɪs.ən ˈkɛr.fəl.i tuː ðə dɪˈstɪŋkt saʊnd ˈdɪf.ɚ.əns bɪˈtwiːn ʃɪp ænd ʃiːp/',
      },
      {
        id: 1,
        start: 5.5,
        end: 10.0,
        text: 'Make sure to smile and stretch your lips wide when pronouncing the long vowel.',
        vi: 'Hãy mỉm cười và mở rộng khóe môi sang hai bên khi phát âm nguyên âm dài.',
        ipa: '/meɪk ʃʊr tuː smaɪl ænd strɛtʃ jɔːr lɪps waɪd wɛn prəˈnaʊn.sɪŋ ðə lɔːŋ ˈvaʊ.əl/',
      },
      {
        id: 2,
        start: 10.5,
        end: 14.5,
        text: 'The large ship sailed smoothly across the calm blue sea.',
        vi: 'Con tàu lớn lướt đi êm ả trên mặt biển xanh êm dịu.',
        ipa: '/ðə lɑːrdʒ ʃɪp seɪld ˈsmuːð.li əˈkrɔːs ðə kɑːm bluː siː/',
      },
      {
        id: 3,
        start: 15.0,
        end: 19.5,
        text: 'A flock of white sheep was grazing on the green hill.',
        vi: 'Một đàn cừu trắng đang thong thả gặm cỏ trên ngọn đồi xanh.',
        ipa: '/ə flɑːk əv waɪt ʃiːp wʌz ˈɡreɪ.zɪŋ ɑːn ðə ɡriːn hɪl/',
      },
    ],
  },
  ipa_th_sound: {
    id: 'ipa_th_sound',
    title: "Mastering the 'TH' Sounds: /θ/ vs /ð/ | Voiced & Voiceless",
    category: 'IPA & Pronunciation',
    level: 'B1 - Intermediate',
    duration: '0:25',
    thumbnailUrl: 'https://img.youtube.com/vi/3s1W_h_Z2cE/hqdefault.jpg',
    description:
      'Master voiced and voiceless TH sounds with accurate tongue placement between teeth.',
    youtubeId: '3s1W_h_Z2cE',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 5.5,
        text: 'Place the tip of your tongue gently between your front teeth.',
        vi: 'Đặt nhẹ đầu lưỡi của bạn vào giữa hai hàm răng cửa.',
        ipa: '/pleɪs ðə tɪp əv jɔːr tʌŋ ˈdʒɛnt.li bɪˈtwiːn jɔːr frʌnt tiːθ/',
      },
      {
        id: 1,
        start: 6.0,
        end: 10.5,
        text: 'Think about three positive things that make you thankful today.',
        vi: 'Hãy nghĩ về ba điều tích cực khiến bạn cảm thấy biết ơn trong ngày hôm nay.',
        ipa: '/θɪŋk əˈbaʊt θriː ˈpɑː.zə.t̬ɪv θɪŋz ðæt meɪk juː ˈθæŋk.fəl təˈdeɪ/',
      },
      {
        id: 2,
        start: 11.0,
        end: 15.5,
        text: 'This is the older brother who lives with their mother and father.',
        vi: 'Đây là người anh trai đang sống cùng với cha và mẹ của họ.',
        ipa: '/ðɪs ɪz ðiː ˈoʊl.dɚ ˈbrʌð.ɚ huː lɪvz wɪð ðɛr ˈmʌð.ɚ ænd ˈfɑː.ðɚ/',
      },
      {
        id: 3,
        start: 16.0,
        end: 21.0,
        text: 'Practice both sounds daily to speak with natural clarity and confidence.',
        vi: 'Luyện tập cả hai âm mỗi ngày để nói rõ ràng và tự tin hơn.',
        ipa: '/ˈpræk.tɪs boʊθ saʊndz ˈdeɪ.li tuː spiːk wɪð ˈnætʃ.ɚ.əl ˈklær.ə.t̬i ænd ˈkɑːn.fə.dəns/',
      },
    ],
  },
  ipa_connected_speech: {
    id: 'ipa_connected_speech',
    title: 'Connected Speech & Linking Words in Natural English',
    category: 'IPA & Pronunciation',
    level: 'B2 - Upper Intermediate',
    duration: '0:26',
    thumbnailUrl: 'https://img.youtube.com/vi/vD-L6l3_c-8/hqdefault.jpg',
    description:
      'Linking consonant to vowel and sound reductions to understand fast natural speech.',
    youtubeId: 'vD-L6l3_c-8',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 5.5,
        text: 'In natural spoken English, words are linked smoothly together.',
        vi: 'Trong văn nói tiếng Anh tự nhiên, các từ được nối liền mạch với nhau.',
        ipa: '/ɪn ˈnætʃ.ɚ.əl ˈspoʊ.kən ˈɪŋ.ɡlɪʃ, wɜːrdz ɑːr lɪŋkt ˈsmuːð.li təˈɡɛð.ɚ/',
      },
      {
        id: 1,
        start: 6.0,
        end: 10.5,
        text: "Notice how the phrase 'pick it up' sounds like a single continuous word.",
        vi: "Hãy chú ý xem cụm 'pick it up' được phát âm liền lại như một từ duy nhất như thế nào.",
        ipa: '/ˈnoʊ.t̬ɪs haʊ ðə freɪz pɪk ɪt ʌp saʊndz laɪk ə ˈsɪŋ.ɡəl kənˈtɪn.ju.əs wɜːrd/',
      },
      {
        id: 2,
        start: 11.0,
        end: 16.0,
        text: "What do you want to do often becomes 'whaddya wanna do' in casual speech.",
        vi: "Câu 'What do you want to do' thường biến thành 'whaddya wanna do' khi nói chuyện thân mật.",
        ipa: '/wʌt duː juː wɑːnt tuː duː ˈɔːf.ən bɪˈkʌmz ˈwʌd.jə ˈwɑː.nə duː ɪn ˈkæʒ.u.əl spiːtʃ/',
      },
      {
        id: 3,
        start: 16.5,
        end: 21.5,
        text: 'Learning linking sounds will dramatically improve your listening comprehension.',
        vi: 'Học cách nối âm sẽ cải thiện vượt bậc khả năng nghe hiểu của bạn.',
        ipa: '/ˈlɜːr.nɪŋ ˈlɪŋ.kɪŋ saʊndz wɪl drəˈmæt̬.ɪ.kəl.i ɪmˈpruːv jɔːr ˈlɪs.ən.ɪŋ ˌkɑːm.prəˈhɛn.ʃən/',
      },
    ],
  },

  // ── Category: US-UK Songs ──
  count_on_me: {
    id: 'count_on_me',
    title: 'Count On Me - Bruno Mars | Acoustic Lyric Dictation',
    category: 'US-UK Songs',
    level: 'A2 - Pre-Intermediate',
    duration: '0:30',
    thumbnailUrl: 'https://img.youtube.com/vi/Yc6T9iY9rs8/hqdefault.jpg',
    description: 'Heartwarming acoustic friendship song by Bruno Mars with clear, melodic diction.',
    youtubeId: 'Yc6T9iY9rs8',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 5.5,
        text: 'If you ever find yourself stuck in the middle of the sea.',
        vi: 'Nếu một ngày nào đó bạn thấy mình bị mắc kẹt giữa đại dương bao la.',
        ipa: '/ɪf juː ˈɛv.ɚ faɪnd jʊərˈsɛlf stʌk ɪn ðə ˈmɪd.əl əv ðə siː/',
      },
      {
        id: 1,
        start: 6.0,
        end: 9.5,
        text: "I'll sail the world to find you.",
        vi: 'Tôi sẽ căng buồm đi khắp thế giới để tìm bạn.',
        ipa: '/aɪl seɪl ðə wɜːrld tuː faɪnd juː/',
      },
      {
        id: 2,
        start: 10.0,
        end: 15.0,
        text: "If you ever find yourself lost in the dark and you can't see.",
        vi: 'Nếu một ngày bạn thấy mình lạc lối trong bóng tối và không thể nhìn thấy gì.',
        ipa: '/ɪf juː ˈɛv.ɚ faɪnd jʊərˈsɛlf lɔːst ɪn ðə dɑːrk ænd juː kænt siː/',
      },
      {
        id: 3,
        start: 15.5,
        end: 20.0,
        text: "I'll be the light to guide you.",
        vi: 'Tôi sẽ là ánh sáng dẫn lối cho bạn.',
        ipa: '/aɪl biː ðə laɪt tuː ɡaɪd juː/',
      },
    ],
  },
  someone_like_you: {
    id: 'someone_like_you',
    title: 'Someone Like You - Adele | Slow & Emotional Dictation',
    category: 'US-UK Songs',
    level: 'B1 - Intermediate',
    duration: '0:28',
    thumbnailUrl: 'https://img.youtube.com/vi/hLQl3WQQoQ0/hqdefault.jpg',
    description:
      'Adele’s iconic ballad featuring rich vocal resonance and standard British English accent.',
    youtubeId: 'hLQl3WQQoQ0',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 7.0,
        text: "I heard that you're settled down, that you found a girl and you're married now.",
        vi: 'Em nghe nói anh đã ổn định cuộc sống, tìm được một người con gái và giờ đã kết hôn.',
        ipa: '/aɪ hɜːrd ðæt jʊər ˈsɛt.əld daʊn, ðæt juː faʊnd ə ɡɜːrl ænd jʊər ˈmær.id naʊ/',
      },
      {
        id: 1,
        start: 7.5,
        end: 14.0,
        text: "I heard that your dreams came true, guess she gave you things I didn't give to you.",
        vi: 'Em nghe nói những giấc mơ của anh đã thành hiện thực, chắc cô ấy đã trao anh những điều em chưa từng có thể.',
        ipa: '/aɪ hɜːrd ðæt jɔːr driːmz keɪm truː, ɡɛs ʃiː ɡeɪv juː θɪŋz aɪ ˈdɪd.ənt ɡɪv tuː juː/',
      },
      {
        id: 2,
        start: 14.5,
        end: 19.5,
        text: "Never mind, I'll find someone like you.",
        vi: 'Đừng bận lòng, em rồi cũng sẽ tìm được một người như anh.',
        ipa: '/ˈnɛv.ɚ maɪnd, aɪl faɪnd ˈsʌm.wʌn laɪk juː/',
      },
      {
        id: 3,
        start: 20.0,
        end: 25.0,
        text: 'I wish nothing but the best for you, too.',
        vi: 'Em không mong gì hơn ngoài những điều tuyệt vời nhất cho anh.',
        ipa: '/aɪ wɪʃ ˈnʌθ.ɪŋ bʌt ðə bɛst fɔːr juː, tuː/',
      },
    ],
  },
  perfect_edsheeran: {
    id: 'perfect_edsheeran',
    title: 'Perfect - Ed Sheeran | Romantic Acoustic Dictation',
    category: 'US-UK Songs',
    level: 'B1 - Intermediate',
    duration: '0:28',
    thumbnailUrl: 'https://img.youtube.com/vi/2Vv-BfVoq4g/hqdefault.jpg',
    description:
      'Ed Sheeran’s romantic acoustic ballad with gentle melody, heartfelt lyrics, and catchy rhymes.',
    youtubeId: '2Vv-BfVoq4g',
    sentences: [
      {
        id: 0,
        start: 1.0,
        end: 6.5,
        text: 'I found a love for me, darling, just dive right in and follow my lead.',
        vi: 'Anh đã tìm thấy tình yêu cho đời mình, em hãy cứ nắm tay anh và hòa mình vào nhé.',
        ipa: '/aɪ faʊnd ə lʌv fɔːr miː, ˈdɑːr.lɪŋ, dʒʌst daɪv raɪt ɪn ænd ˈfɑː.loʊ maɪ liːd/',
      },
      {
        id: 1,
        start: 7.0,
        end: 12.0,
        text: 'Well, I found a girl, beautiful and sweet.',
        vi: 'Anh đã tìm thấy một người con gái, thật xinh đẹp và dịu dàng.',
        ipa: '/wɛl, aɪ faʊnd ə ɡɜːrl, ˈbjuː.t̬ə.fəl ænd swiːt/',
      },
      {
        id: 2,
        start: 12.5,
        end: 18.0,
        text: 'I never knew you were the someone waiting for me.',
        vi: 'Anh chưa từng nghĩ rằng em chính là người bấy lâu nay vẫn luôn chờ đợi anh.',
        ipa: '/aɪ ˈnɛv.ɚ nuː juː wɜːr ðə ˈsʌm.wʌn ˈweɪ.tɪŋ fɔːr miː/',
      },
      {
        id: 3,
        start: 18.5,
        end: 24.5,
        text: 'We were just kids when we fell in love, not knowing what it was.',
        vi: 'Chúng ta chỉ là những đứa trẻ khi vừa biết yêu, chưa từng hiểu trọn vẹn tình yêu là gì.',
        ipa: '/wiː wɜːr dʒʌst kɪdz wɛn wiː fɛl ɪn lʌv, nɑːt ˈnoʊ.ɪŋ wʌt ɪt wʌz/',
      },
    ],
  },
}

export const DEFAULT_LESSON = LESSON_DATABASE.kiki
